//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EquifaxInterfaceException
    {
        
        private statusResponse statusField;
        
        private bool statusFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public statusResponse status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public enum statusResponse
    {
        
        /// <remarks/>
        RSP_SUCCESS,
        
        /// <remarks/>
        RSP_ERROR,
        
        /// <remarks/>
        RSP_EC,
        
        /// <remarks/>
        RSP_EC_SERV_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_CA_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_PM_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_OP2_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_EMAIL_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_IDV_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_EXPERT_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_DAS_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_RIO_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_SERV_DF_NOT_AVAILABLE,
        
        /// <remarks/>
        RSP_EC_REQ_INCORRECT,
        
        /// <remarks/>
        RSP_EC_REQ_HEADER_INCORRECT,
        
        /// <remarks/>
        RSP_EC_REQ_NOT_AUTHENTICATED,
        
        /// <remarks/>
        RSP_EC_REQ_NOT_AUTHORIZED,
        
        /// <remarks/>
        RSP_EC_REQ_TIMEOUT,
        
        /// <remarks/>
        RSP_EC_REQ_VERY_BIG,
        
        /// <remarks/>
        RSP_EC_REQ_URL_VERY_LONG,
        
        /// <remarks/>
        RSP_EC_REQ_MEDIA_TYPE_INCORRECT,
        
        /// <remarks/>
        RSP_EI,
        
        /// <remarks/>
        RSP_EI_VALUES_NULL,
        
        /// <remarks/>
        RSP_EI_CA_TOKEN_NULL,
        
        /// <remarks/>
        RSP_EI_OP2_COD_ENTI_NULL,
        
        /// <remarks/>
        RSP_EI_VALUES_EMPTY,
        
        /// <remarks/>
        RSP_EI_CA_TOKEN_EMPTY,
        
        /// <remarks/>
        RSP_EI_VALUES_INCORRECT,
        
        /// <remarks/>
        RSP_EI_CA_TOKEN_INCORRECT,
        
        /// <remarks/>
        RSP_EI_CA_USER_INCORRECT,
        
        /// <remarks/>
        RSP_EI_CA_PWD_INCORRECT,
        
        /// <remarks/>
        RSP_EI_SESSION_INVALID,
        
        /// <remarks/>
        RSP_EI_COOKIES_INVALID,
        
        /// <remarks/>
        RSP_EI_SESSION_EXPIRED,
        
        /// <remarks/>
        RSP_EI_IP_NO_AUTHORIZED,
        
        /// <remarks/>
        RSP_EI_PARAMS_INCORRECT,
        
        /// <remarks/>
        RSP_EB,
        
        /// <remarks/>
        RSP_EB_BUSINESS_RULE_INCORRECT,
        
        /// <remarks/>
        RSP_EB_OPERATION_INCORRECT,
        
        /// <remarks/>
        RSP_EB_FILE_NOT_GENERATE,
        
        /// <remarks/>
        RSP_ED,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_NOT_FOUND,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_NOT_GET,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_NOT_INSERT,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_NOT_DELETE,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_NOT_UPDATE,
        
        /// <remarks/>
        RSP_ED_DATASOURCE_TIMEOUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class GetReporteHistoricoResponse
    {
        
        private object reporteCrediticioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        public object ReporteCrediticio
        {
            get
            {
                return this.reporteCrediticioField;
            }
            set
            {
                this.reporteCrediticioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
    public partial class HistoricType
    {
        
        private string numeroDeOperacionField;
        
        private string codigoReporteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumeroDeOperacion
        {
            get
            {
                return this.numeroDeOperacionField;
            }
            set
            {
                this.numeroDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CodigoReporte
        {
            get
            {
                return this.codigoReporteField;
            }
            set
            {
                this.codigoReporteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class GetReporteHistorico
    {
        
        private HistoricType consultaHistoricaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        public HistoricType ConsultaHistorica
        {
            get
            {
                return this.consultaHistoricaField;
            }
            set
            {
                this.consultaHistoricaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EntityAccountHist
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private AmountDebtHist[] montosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] Montos
        {
            get
            {
                return this.montosField;
            }
            set
            {
                this.montosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class AmountDebtHist
    {
        
        private string periodoField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class AccountDebtHist
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private AmountDebtHist[] montosField;
        
        private AccountDebtHist[] cuentasField;
        
        private EntityAccountHist[] entidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] Montos
        {
            get
            {
                return this.montosField;
            }
            set
            {
                this.montosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cuenta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountDebtHist[] Cuentas
        {
            get
            {
                return this.cuentasField;
            }
            set
            {
                this.cuentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityAccountHist[] Entidades
        {
            get
            {
                return this.entidadesField;
            }
            set
            {
                this.entidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class SummaryNodeHist
    {
        
        private AccountDebtHist[] cuentasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cuenta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountDebtHist[] Cuentas
        {
            get
            {
                return this.cuentasField;
            }
            set
            {
                this.cuentasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class QuotaDebtHist
    {
        
        private string tipoBancaField;
        
        private string tipoDeudaField;
        
        private AmountDebtHist[] lineaTotalField;
        
        private AmountDebtHist[] saldoUltimoMesField;
        
        private AmountDebtHist[] saldoPromedioField;
        
        private AmountDebtHist[] cuotaMensualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TipoBanca
        {
            get
            {
                return this.tipoBancaField;
            }
            set
            {
                this.tipoBancaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TipoDeuda
        {
            get
            {
                return this.tipoDeudaField;
            }
            set
            {
                this.tipoDeudaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] LineaTotal
        {
            get
            {
                return this.lineaTotalField;
            }
            set
            {
                this.lineaTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] SaldoUltimoMes
        {
            get
            {
                return this.saldoUltimoMesField;
            }
            set
            {
                this.saldoUltimoMesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] SaldoPromedio
        {
            get
            {
                return this.saldoPromedioField;
            }
            set
            {
                this.saldoPromedioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Monto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AmountDebtHist[] CuotaMensual
        {
            get
            {
                return this.cuotaMensualField;
            }
            set
            {
                this.cuotaMensualField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EntityQuotaDebtHist
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private QuotaDebtHist[] deudasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Deuda", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public QuotaDebtHist[] Deudas
        {
            get
            {
                return this.deudasField;
            }
            set
            {
                this.deudasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EntityReportedHist
    {
        
        private string periodoField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class SummaryDebtHist
    {
        
        private EntityReportedHist[] entidadesReportadasField;
        
        private EntityQuotaDebtHist[] entidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NroReportados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityReportedHist[] EntidadesReportadas
        {
            get
            {
                return this.entidadesReportadasField;
            }
            set
            {
                this.entidadesReportadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityQuotaDebtHist[] Entidades
        {
            get
            {
                return this.entidadesField;
            }
            set
            {
                this.entidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class HistoricalQuota
    {
        
        private SummaryDebtHist deudasSupervisadasField;
        
        private SummaryDebtHist deudasNoSupervisadasField;
        
        private SummaryDebtHist deudasPersonalesField;
        
        private SummaryNodeHist garantiasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SummaryDebtHist DeudasSupervisadas
        {
            get
            {
                return this.deudasSupervisadasField;
            }
            set
            {
                this.deudasSupervisadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SummaryDebtHist DeudasNoSupervisadas
        {
            get
            {
                return this.deudasNoSupervisadasField;
            }
            set
            {
                this.deudasNoSupervisadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SummaryDebtHist DeudasPersonales
        {
            get
            {
                return this.deudasPersonalesField;
            }
            set
            {
                this.deudasPersonalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public SummaryNodeHist Garantias
        {
            get
            {
                return this.garantiasField;
            }
            set
            {
                this.garantiasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EntityAccountCurrent
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified
        {
            get
            {
                return this.montoFieldSpecified;
            }
            set
            {
                this.montoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class AccountDebtCurrent
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        private AccountDebtCurrent[] cuentasField;
        
        private EntityAccountCurrent[] entidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified
        {
            get
            {
                return this.montoFieldSpecified;
            }
            set
            {
                this.montoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cuenta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountDebtCurrent[] Cuentas
        {
            get
            {
                return this.cuentasField;
            }
            set
            {
                this.cuentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityAccountCurrent[] Entidades
        {
            get
            {
                return this.entidadesField;
            }
            set
            {
                this.entidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class SummaryNodeCurrent
    {
        
        private AccountDebtCurrent[] cuentasField;
        
        private string periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cuenta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AccountDebtCurrent[] Cuentas
        {
            get
            {
                return this.cuentasField;
            }
            set
            {
                this.cuentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class QuotaDebtCurrent
    {
        
        private string tipoBancaField;
        
        private string tipoDeudaField;
        
        private decimal lineaTotalField;
        
        private bool lineaTotalFieldSpecified;
        
        private decimal saldoUltimoMesField;
        
        private bool saldoUltimoMesFieldSpecified;
        
        private decimal saldoPromedioField;
        
        private bool saldoPromedioFieldSpecified;
        
        private decimal cuotaMensualField;
        
        private bool cuotaMensualFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TipoBanca
        {
            get
            {
                return this.tipoBancaField;
            }
            set
            {
                this.tipoBancaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TipoDeuda
        {
            get
            {
                return this.tipoDeudaField;
            }
            set
            {
                this.tipoDeudaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal LineaTotal
        {
            get
            {
                return this.lineaTotalField;
            }
            set
            {
                this.lineaTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineaTotalSpecified
        {
            get
            {
                return this.lineaTotalFieldSpecified;
            }
            set
            {
                this.lineaTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal SaldoUltimoMes
        {
            get
            {
                return this.saldoUltimoMesField;
            }
            set
            {
                this.saldoUltimoMesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaldoUltimoMesSpecified
        {
            get
            {
                return this.saldoUltimoMesFieldSpecified;
            }
            set
            {
                this.saldoUltimoMesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal SaldoPromedio
        {
            get
            {
                return this.saldoPromedioField;
            }
            set
            {
                this.saldoPromedioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaldoPromedioSpecified
        {
            get
            {
                return this.saldoPromedioFieldSpecified;
            }
            set
            {
                this.saldoPromedioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal CuotaMensual
        {
            get
            {
                return this.cuotaMensualField;
            }
            set
            {
                this.cuotaMensualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CuotaMensualSpecified
        {
            get
            {
                return this.cuotaMensualFieldSpecified;
            }
            set
            {
                this.cuotaMensualFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class EntityQuotaDebtCurrent
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private QuotaDebtCurrent[] deudasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Deuda", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public QuotaDebtCurrent[] Deudas
        {
            get
            {
                return this.deudasField;
            }
            set
            {
                this.deudasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class SummaryDebtCurrent
    {
        
        private EntityQuotaDebtCurrent[] entidadesField;
        
        private string periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityQuotaDebtCurrent[] Entidades
        {
            get
            {
                return this.entidadesField;
            }
            set
            {
                this.entidadesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class CurrentQuota
    {
        
        private SummaryDebtCurrent deudasSupervisadasField;
        
        private SummaryDebtCurrent deudasNoSupervisadasField;
        
        private SummaryDebtCurrent deudasPersonalesField;
        
        private SummaryNodeCurrent garantiasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SummaryDebtCurrent DeudasSupervisadas
        {
            get
            {
                return this.deudasSupervisadasField;
            }
            set
            {
                this.deudasSupervisadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SummaryDebtCurrent DeudasNoSupervisadas
        {
            get
            {
                return this.deudasNoSupervisadasField;
            }
            set
            {
                this.deudasNoSupervisadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SummaryDebtCurrent DeudasPersonales
        {
            get
            {
                return this.deudasPersonalesField;
            }
            set
            {
                this.deudasPersonalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public SummaryNodeCurrent Garantias
        {
            get
            {
                return this.garantiasField;
            }
            set
            {
                this.garantiasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class GetReporteOnlineResponse
    {
        
        private object reporteCrediticioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        public object ReporteCrediticio
        {
            get
            {
                return this.reporteCrediticioField;
            }
            set
            {
                this.reporteCrediticioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint")]
    public partial class GetReporteOnline
    {
        
        private QueryDataType datosConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        public QueryDataType DatosConsulta
        {
            get
            {
                return this.datosConsultaField;
            }
            set
            {
                this.datosConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
    public partial class QueryDataType
    {
        
        private string tipoPersonaField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string codigoReporteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoReporte
        {
            get
            {
                return this.codigoReporteField;
            }
            set
            {
                this.codigoReporteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.creditreport.equifax.com.pe/endpoint", ConfigurationName="ServiceReference2.Endpoint")]
    public interface Endpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.EquifaxInterfaceException), Action="", Name="EquifaxInterfaceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteHistoricoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteHistorico))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HistoricalQuota))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrentQuota))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteOnlineResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteOnline))]
        System.Threading.Tasks.Task<ServiceReference2.GetReporteOnlineResponse1> GetReporteOnlineAsync(ServiceReference2.GetReporteOnline1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.EquifaxInterfaceException), Action="", Name="EquifaxInterfaceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteHistoricoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteHistorico))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HistoricalQuota))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrentQuota))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteOnlineResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetReporteOnline))]
        System.Threading.Tasks.Task<ServiceReference2.GetReporteHistoricoResponse1> GetReporteHistoricoAsync(ServiceReference2.GetReporteHistorico1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReporteOnline", WrapperNamespace="http://ws.creditreport.equifax.com.pe/endpoint", IsWrapped=true)]
    public partial class GetReporteOnline1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
        public ServiceReference2.QueryDataType DatosConsulta;
        
        public GetReporteOnline1()
        {
        }
        
        public GetReporteOnline1(ServiceReference2.QueryDataType DatosConsulta)
        {
            this.DatosConsulta = DatosConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReporteOnlineResponse", WrapperNamespace="http://ws.creditreport.equifax.com.pe/endpoint", IsWrapped=true)]
    public partial class GetReporteOnlineResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
        public object ReporteCrediticio;
        
        public GetReporteOnlineResponse1()
        {
        }
        
        public GetReporteOnlineResponse1(object ReporteCrediticio)
        {
            this.ReporteCrediticio = ReporteCrediticio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReporteHistorico", WrapperNamespace="http://ws.creditreport.equifax.com.pe/endpoint", IsWrapped=true)]
    public partial class GetReporteHistorico1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
        public ServiceReference2.HistoricType ConsultaHistorica;
        
        public GetReporteHistorico1()
        {
        }
        
        public GetReporteHistorico1(ServiceReference2.HistoricType ConsultaHistorica)
        {
            this.ConsultaHistorica = ConsultaHistorica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReporteHistoricoResponse", WrapperNamespace="http://ws.creditreport.equifax.com.pe/endpoint", IsWrapped=true)]
    public partial class GetReporteHistoricoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ws.creditreport.equifax.com.pe/document")]
        public object ReporteCrediticio;
        
        public GetReporteHistoricoResponse1()
        {
        }
        
        public GetReporteHistoricoResponse1(object ReporteCrediticio)
        {
            this.ReporteCrediticio = ReporteCrediticio;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface EndpointChannel : ServiceReference2.Endpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EndpointClient : System.ServiceModel.ClientBase<ServiceReference2.Endpoint>, ServiceReference2.Endpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EndpointClient() : 
                base(EndpointClient.GetDefaultBinding(), EndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CreditReportPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(EndpointClient.GetBindingForEndpoint(endpointConfiguration), EndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetReporteOnlineResponse1> ServiceReference2.Endpoint.GetReporteOnlineAsync(ServiceReference2.GetReporteOnline1 request)
        {
            return base.Channel.GetReporteOnlineAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetReporteOnlineResponse1> GetReporteOnlineAsync(ServiceReference2.QueryDataType DatosConsulta)
        {
            ServiceReference2.GetReporteOnline1 inValue = new ServiceReference2.GetReporteOnline1();
            inValue.DatosConsulta = DatosConsulta;
            return ((ServiceReference2.Endpoint)(this)).GetReporteOnlineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetReporteHistoricoResponse1> ServiceReference2.Endpoint.GetReporteHistoricoAsync(ServiceReference2.GetReporteHistorico1 request)
        {
            return base.Channel.GetReporteHistoricoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetReporteHistoricoResponse1> GetReporteHistoricoAsync(ServiceReference2.HistoricType ConsultaHistorica)
        {
            ServiceReference2.GetReporteHistorico1 inValue = new ServiceReference2.GetReporteHistorico1();
            inValue.ConsultaHistorica = ConsultaHistorica;
            return ((ServiceReference2.Endpoint)(this)).GetReporteHistoricoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditReportPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditReportPort))
            {
                return new System.ServiceModel.EndpointAddress("https://accepwse.equifax.com.pe/CreditReportService/Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EndpointClient.GetBindingForEndpoint(EndpointConfiguration.CreditReportPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EndpointClient.GetEndpointAddress(EndpointConfiguration.CreditReportPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CreditReportPort,
        }
    }
}
